In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [5]:
data = pd.read_csv('heart.csv')

In [17]:
data.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [10]:
data.isnull().sum()
data.fillna(data.median(), inplace=True)

In [21]:
#one-hot encoded
categorical_columns = ["sex", "fbs", "restecg", "exang", "ca", "thal"]


data_encoded = pd.get_dummies(data, columns=categorical_columns)


data_encoded.to_csv('your_encoded_dataset.csv', index=False)

In [24]:
newdata = pd.read_csv('your_encoded_dataset.csv')
newdata.head(5)

age  cp  trestbps  chol  thalach  oldpeak  slope  target  sex_0  sex_1  \
0   52   0       125   212      168      1.0      2       0      0      1   
1   53   0       140   203      155      3.1      0       0      0      1   
2   70   0       145   174      125      2.6      0       0      0      1   
3   61   0       148   203      161      0.0      2       0      0      1   
4   62   0       138   294      106      1.9      1       0      1      0   

   ...  exang_1  ca_0  ca_1  ca_2  ca_3  ca_4  thal_0  thal_1  thal_2  thal_3  
0  ...        0     0     0     1     0     0       0       0       0       1  
1  ...        1     1     0     0     0     0       0       0       0       1  
2  ...        1     1     0     0     0     0       0       0       0       1  
3  ...        0     0     1     0     0     0       0       0       0       1  
4  ...        0     0     0     0     1     0       0       0       1       0  

[5 rows x 26 columns]

In [ ]:
#one hot encoding 

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Load your dataset (replace 'your_dataset.csv' with your dataset file)
data = pd.read_csv('one_hot.csv')

# Split the dataset into features (X) and the target variable (y)
X = data.drop('target', axis=1)
y = data['target']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features (optional but often improves model performance)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize the Logistic Regression model
model = LogisticRegression()

# Train the model on the training data
model.fit(X_train, y_train)

# Evaluate the model on the testing data
y_pred = model.predict(X_test)

# Model Evaluation
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print evaluation metrics
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")
print(f"ROC AUC Score: {roc_auc:.2f}")

print("Confusion Matrix:")
print(conf_matrix)

print("Classification Report:")
print(classification_rep)


Accuracy: 0.82
Precision: 0.80
Recall: 0.86
F1 Score: 0.83
ROC AUC Score: 0.90
Confusion Matrix:
[[80 22]
 [14 89]]
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.78      0.82       102
           1       0.80      0.86      0.83       103

    accuracy                           0.82       205
   macro avg       0.83      0.82      0.82       205
weighted avg       0.83      0.82      0.82       205



#without encoding


In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Load your dataset (replace 'your_dataset.csv' with your dataset file)
data = pd.read_csv('heart.csv')

# Split the dataset into features (X) and the target variable (y)
X = data.drop('target', axis=1)
y = data['target']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features (optional but often improves model performance)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize the Logistic Regression model
model = LogisticRegression()

# Train the model on the training data
model.fit(X_train, y_train)

# Evaluate the model on the testing data
y_pred = model.predict(X_test)

# Model Evaluation
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print evaluation metrics
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")
print(f"ROC AUC Score: {roc_auc:.2f}")

print("Confusion Matrix:")
print(conf_matrix)

print("Classification Report:")
print(classification_rep)


Accuracy: 0.80
Precision: 0.76
Recall: 0.87
F1 Score: 0.81
ROC AUC Score: 0.88
Confusion Matrix:
[[73 29]
 [13 90]]
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.72      0.78       102
           1       0.76      0.87      0.81       103

    accuracy                           0.80       205
   macro avg       0.80      0.79      0.79       205
weighted avg       0.80      0.80      0.79       205



#with label encoding

In [18]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load your dataset (replace 'your_dataset.csv' with your dataset file)
data = pd.read_csv('heart.csv')

# Define the list of ordinal features to label encode
ordinal_features = ['cp', 'thal']

# Apply label encoding to each ordinal feature
label_encoder = LabelEncoder()
for feature in ordinal_features:
    data[feature] = label_encoder.fit_transform(data[feature])

# Save the dataset with label encoding applied
data.to_csv('le.csv', index=False)

In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Load your dataset (replace 'your_dataset.csv' with your dataset file)
data = pd.read_csv('le.csv')

# Split the dataset into features (X) and the target variable (y)
X = data.drop('target', axis=1)
y = data['target']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features (optional but often improves model performance)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize the Logistic Regression model
model = LogisticRegression()

# Train the model on the training data
model.fit(X_train, y_train)

# Evaluate the model on the testing data
y_pred = model.predict(X_test)

# Model Evaluation
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print evaluation metrics
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")
print(f"ROC AUC Score: {roc_auc:.2f}")

print("Confusion Matrix:")
print(conf_matrix)

print("Classification Report:")
print(classification_rep)


Accuracy: 0.80
Precision: 0.76
Recall: 0.87
F1 Score: 0.81
ROC AUC Score: 0.88
Confusion Matrix:
[[73 29]
 [13 90]]
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.72      0.78       102
           1       0.76      0.87      0.81       103

    accuracy                           0.80       205
   macro avg       0.80      0.79      0.79       205
weighted avg       0.80      0.80      0.79       205



#cross validating

In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Load your dataset (replace 'your_dataset.csv' with your dataset file)
data = pd.read_csv('le.csv')

# Split the dataset into features (X) and the target variable (y)
X = data.drop('target', axis=1)
y = data['target']

# Standardize features (optional but often improves model performance)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Initialize the Logistic Regression model
model = LogisticRegression()

# Perform k-fold cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=42)

accuracy_scores = cross_val_score(model, X, y, cv=kf, scoring='accuracy')
precision_scores = cross_val_score(model, X, y, cv=kf, scoring='precision')
recall_scores = cross_val_score(model, X, y, cv=kf, scoring='recall')
f1_scores = cross_val_score(model, X, y, cv=kf, scoring='f1')
roc_auc_scores = cross_val_score(model, X, y, cv=kf, scoring='roc_auc')

# Print cross-validated metrics
print(f"Cross-Validated Accuracy: {accuracy_scores.mean():.2f}")
print(f"Cross-Validated Precision: {precision_scores.mean():.2f}")
print(f"Cross-Validated Recall: {recall_scores.mean():.2f}")
print(f"Cross-Validated F1 Score: {f1_scores.mean():.2f}")
print(f"Cross-Validated ROC AUC Score: {roc_auc_scores.mean():.2f}")


Cross-Validated Accuracy: 0.85
Cross-Validated Precision: 0.82
Cross-Validated Recall: 0.89
Cross-Validated F1 Score: 0.86
Cross-Validated ROC AUC Score: 0.91


In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Load your dataset (replace 'your_dataset.csv' with your dataset file)
data = pd.read_csv('one_hot.csv')

# Split the dataset into features (X) and the target variable (y)
X = data.drop('target', axis=1)
y = data['target']

# Standardize features (optional but often improves model performance)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Initialize the Logistic Regression model
model = LogisticRegression()

# Perform k-fold cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=42)

accuracy_scores = cross_val_score(model, X, y, cv=kf, scoring='accuracy')
precision_scores = cross_val_score(model, X, y, cv=kf, scoring='precision')
recall_scores = cross_val_score(model, X, y, cv=kf, scoring='recall')
f1_scores = cross_val_score(model, X, y, cv=kf, scoring='f1')
roc_auc_scores = cross_val_score(model, X, y, cv=kf, scoring='roc_auc')

# Print cross-validated metrics
print(f"Cross-Validated Accuracy: {accuracy_scores.mean():.2f}")
print(f"Cross-Validated Precision: {precision_scores.mean():.2f}")
print(f"Cross-Validated Recall: {recall_scores.mean():.2f}")
print(f"Cross-Validated F1 Score: {f1_scores.mean():.2f}")
print(f"Cross-Validated ROC AUC Score: {roc_auc_scores.mean():.2f}")


Cross-Validated Accuracy: 0.85
Cross-Validated Precision: 0.84
Cross-Validated Recall: 0.89
Cross-Validated F1 Score: 0.86
Cross-Validated ROC AUC Score: 0.93
